# Generated by Django 4.2.2 on 2023-06-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('business', models.CharField(max_length=255)),
                ('seller', models.CharField(max_length=255)),
                ('business_price', models.IntegerField()),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('introduction', models.TextField(max_length=1000)),
                ('number', models.IntegerField()),
                ('token_paid', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
