# Generated by Django 4.2.2 on 2023-06-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessapp', '0002_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
