# Generated by Django 4.2.2 on 2023-06-14 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessapp', '0003_business_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='business_price',
            new_name='businessprice',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='token_paid',
            new_name='tokenpaid',
        ),
    ]
