# Generated by Django 4.2.2 on 2023-06-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessapp', '0004_rename_business_price_purchase_businessprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='tokenpaid',
            field=models.IntegerField(),
        ),
    ]
